/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Antique_Globe.glb 
Author: thelowestanimal (https://sketchfab.com/thelowestanimal)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/antique-globe-a30fc85dd7764b3bb45f509a38c0d000
Title: Antique Globe
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Antique_Globe(props) {
  const { nodes, materials } = useGLTF('/Antique_Globe.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <mesh geometry={nodes.Object_5.geometry} material={materials.material} position={[114.526, -5.579, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Antique_Globe.glb')
