/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Antique_Scene.glb 
Author: Paris (https://sketchfab.com/AAAAAAAAAbla)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/small-antique-table-asset-036d3d0f15a14cff8e1c122072ef87d2
Title: Small Antique Table Asset
*/

import React, { useRef, useState } from 'react'
import { useFrame } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei'

export function Antique_Scene(props) {
  const { nodes, materials } = useGLTF('/Antique_Scene.glb')

  const [isHovered, setIsHovered] = useState(false)
  const paperRef = useRef();

  useFrame((state, delta) =>{
    if(isHovered) paperRef.current.position.y = Math.abs(Math.sin(state.clock.elapsedTime)) * 2 +31.34;
  })

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.026}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-7.114, 31.033, 10.374]} rotation={[0.88, 0.557, 0.258]} scale={[0.125, 0.125, 0.188]}>
            <mesh geometry={nodes.Clock_Clockk_0.geometry} material={materials.Clockk} position={[13.375, 10.201, 4.818]} />
          </group>
          <group position={[1.338, 30.115, 14.571]} rotation={[0, -Math.PI / 2, 0]} scale={0.597}>
            <mesh geometry={nodes.Table_Tablea_0.geometry} material={materials.Tablea} position={[0, -5.056, -27.197]} />
          </group>
          <group position={[5.641, 33.027, 4.531]} rotation={[Math.PI / 2, 0, -2.967]} scale={[0.374, 0.374, 0.206]}>
            <mesh geometry={nodes.book4_low001_BooksWhNames_0.geometry} material={materials.BooksWhNames} position={[0, 0, -5.297]} />
          </group>
          <group position={[4.714, 34.12, 4.439]} rotation={[Math.PI / 2, 0, 2.88]} scale={[0.326, 0.311, 0.058]}>
            <mesh geometry={nodes.book5_low001_BooksWhNames_0.geometry} material={materials.BooksWhNames} position={[0, 0, -5.297]} />
          </group>
          <group position={[-8.336, 31.044, 1.828]} rotation={[Math.PI / 2, 0, 2.967]} scale={0.374}>
            <mesh geometry={nodes.book2_low001_BooksWhNames_0.geometry} material={materials.BooksWhNames} position={[0, 0, -5.297]} />
          </group>
          <group position={[5.72, 34.429, 4.733]} rotation={[Math.PI / 2, 0, -2.094]} scale={[0.28, 0.28, 0.381]}>
            <mesh geometry={nodes.book1_low001_BooksWhNames_0.geometry} material={materials.BooksWhNames} position={[0, 0, -5.297]} />
          </group>
          <group position={[4.836, 31.044, 7.146]} rotation={[Math.PI / 2, 0, 2.356]} scale={0.374}>
            <mesh geometry={nodes.book3_low001_BooksWhNames_0.geometry} material={materials.BooksWhNames} position={[0, 0, -5.297]} />
          </group>
          <group position={[10.766, 0, 42.695]} rotation={[-Math.PI / 2, 0, 0.436]} scale={0.259}>
            <mesh geometry={nodes.Sit_Stooll_0.geometry} material={materials.Stooll} position={[0, 0, 61.303]} />
          </group>
          <group position={[10.766, 0, 42.695]} rotation={[0, -1.134, 0]} scale={[0.239, 0.236, 0.259]}>
            <mesh geometry={nodes.Stool_Stooll_0.geometry} material={materials.Stooll} position={[22.777, 52.695, 0]} />
          </group>
          <group position={[-7.114, 34.412, 12.433]} rotation={[1.396, 1.222, -Math.PI]}>
            <mesh geometry={nodes.Clock_Arrow_L_Clockk_0.geometry} material={materials.Clockk} position={[1.575, 1.129, -2.224]} rotation={[2.625, 0.557, 0.258]} scale={[0.125, 0.125, 0.188]} />
          </group>
          <group position={[-7.114, 34.412, 12.433]} rotation={[1.396, -1.134, Math.PI]}>
            <mesh geometry={nodes.Clock_Arrow_S_Clockk_0.geometry} material={materials.Clockk} position={[1.575, 1.129, -2.224]} rotation={[2.625, 0.557, 0.258]} scale={[0.125, 0.125, 0.188]} />
          </group>
          <mesh geometry={nodes.Table_Pac_Tablea_0.geometry} material={materials.Tablea} position={[1.382, 28.232, 32.037]} scale={0.394} />
          <mesh geometry={nodes.Candelabra_Candelabra_0.geometry} material={materials.Candelabra} position={[10.168, 31.044, 13.531]} rotation={[-Math.PI / 2, 0, -0.873]} scale={0.394} />
          <mesh geometry={nodes.page_low_Pagee_0.geometry} material={materials.Pagee} position={[-10, 31.334, 24.693]} rotation={[-Math.PI / 2, 0, 0]} scale={0.201} 
            ref={paperRef}
            onPointerEnter={(event) => {event.stopPropagation(), setIsHovered(true)}}
            onPointerLeave={() => {setIsHovered(false)}}/>
          <mesh geometry={nodes['Plane001_Material_#3_0'].geometry} material={materials.Material_3} position={[10.222, 56.981, 13.445]} scale={0.195} />
          <mesh geometry={nodes['Plane002_Material_#3_0'].geometry} material={materials.Material_3} position={[10.222, 56.981, 13.445]} rotation={[0, -Math.PI / 2, 0]} scale={0.195} />
          <mesh geometry={nodes['Plane003_Material_#3_0'].geometry} material={materials.Material_3} position={[14.618, 54.894, 18.235]} scale={0.195} />
          <mesh geometry={nodes['Plane004_Material_#3_0'].geometry} material={materials.Material_3} position={[14.618, 54.894, 18.235]} rotation={[0, -Math.PI / 2, 0]} scale={0.195} />
          <mesh geometry={nodes['Plane005_Material_#3_0'].geometry} material={materials.Material_3} position={[5.705, 54.894, 8.855]} scale={0.195} />
          <mesh geometry={nodes['Plane006_Material_#3_0'].geometry} material={materials.Material_3} position={[5.705, 54.894, 8.855]} rotation={[0, -Math.PI / 2, 0]} scale={0.195} />
          <mesh geometry={nodes.Plane007_Floor_0.geometry} material={materials.Floor} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.coin1_low_coinss_0.geometry} material={materials.coinss} position={[-10.712, 31.066, 16.391]} rotation={[-Math.PI / 2, 0, -0.611]} scale={[0.003, 0.003, 0.002]} />
          <mesh geometry={nodes.coin2_low_coinss_0.geometry} material={materials.coinss} position={[-8.926, 31.066, 17.951]} rotation={[-Math.PI / 2, 0, 1.134]} scale={[0.003, 0.003, 0.002]} />
          <mesh geometry={nodes.coin2_low001_coinss_0.geometry} material={materials.coinss} position={[6.354, 36.502, 6.848]} rotation={[Math.PI / 2, 0, 2.793]} scale={[0.003, 0.003, 0.002]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Antique_Scene.glb')
