/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Chair.glb --transform 
Files: Chair.glb [3.36MB] > C:\Users\janae\Desktop\Travel Planner App\Travel-Planner-App\frontend\my-travel-app\public\Chair-transformed.glb [313.94KB] (91%)
Author: shuvalov.di (https://sketchfab.com/shuvalov.di)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/chair-02f920ac307b47dda8d6fa14e5fe1da5
Title: Chair
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Chair(props) {
  const { nodes, materials } = useGLTF('/Chair-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Chair_Chair_0.geometry} material={materials.Chair} rotation={[-Math.PI / 2, 0, 0]} scale={1.194} castshadow receiveShadow/>
    </group>
  )
}

useGLTF.preload('/Chair-transformed.glb')
