/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Dragon.glb --transform 
Files: Dragon.glb [347.46KB] > C:\Users\janae\Desktop\Travel Planner App\Travel-Planner-App\frontend\my-travel-app\public\Dragon-transformed.glb [48.81KB] (86%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Dragon(props) {
  const { nodes, materials } = useGLTF('/Dragon-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Root} />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <skinnedMesh geometry={nodes.DragonMesh_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.DragonMesh_1.skeleton} material-color="hotpink" />
        <skinnedMesh geometry={nodes.DragonMesh_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.DragonMesh_2.skeleton} material-color="hotpink"/>
        <skinnedMesh geometry={nodes.DragonMesh_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.DragonMesh_3.skeleton} material-color="hotpink"/>
        <skinnedMesh geometry={nodes.DragonMesh_4.geometry} material={materials.PaletteMaterial001} skeleton={nodes.DragonMesh_4.skeleton} material-color="hotpink"/>
        <skinnedMesh geometry={nodes.DragonMesh_5.geometry} material={materials.PaletteMaterial001} skeleton={nodes.DragonMesh_5.skeleton} material-color="hotpink"/>
        <skinnedMesh geometry={nodes.DragonMesh_6.geometry} material={materials.PaletteMaterial001} skeleton={nodes.DragonMesh_6.skeleton} material-color="hotpink"/>
      </group>
    </group>
  )
}

useGLTF.preload('/Dragon-transformed.glb')
