/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Passport.glb --transform 
Files: Passport.glb [2.14MB] > C:\Users\janae\Desktop\Travel Planner App\Travel-Planner-App\frontend\my-travel-app\public\Passport-transformed.glb [247.52KB] (88%)
Author: TheSlavarik (https://sketchfab.com/TheSlavarik)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/personal-id-8c87177c4a8d4f119dd90cb938cd4e2c
Title: Personal ID
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export function Passport(props) {
  const { nodes, materials } = useGLTF('/Passport-transformed.glb')

  const [isHovered, setIsHovered] = useState(false)
  const passportRef = useRef();

  useFrame((state, delta) =>{
    if(isHovered) passportRef.current.rotation.y = Math.abs(Math.sin(state.clock.elapsedTime)) * 1.2;
  })

  return (
    <group {...props} 
      ref={passportRef}
      dispose={null} 
      onPointerEnter={(event) => {event.stopPropagation(), setIsHovered(true)}}
      onPointerLeave={() => {setIsHovered(false)}}>
      <mesh geometry={nodes.Cube_Material_0.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} material-color="beige" castShadow receiveShadow/>
    </group>
  )
}

useGLTF.preload('/Passport-transformed.glb')
